version: '3.3'
services:
  elasticsearch:
    container_name: elasticsearch_single_node
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      - node.name=elasticsearch_single_node
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1
    container_name: elasticsearch_single_node-kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch_single_node:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch_single_node:9200
    ports:
      - 5601:5601
    networks:
      - elastic
  
volumes:
  es-data:
    driver: local

networks:
  elastic:
    driver: bridge